import esbuild from "esbuild";
import fs from "fs";
import { createRequire } from "module";
import path from "path";

const require = createRequire(import.meta.url);
const prod = process.argv.includes("production");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;


const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
];

const nodeCoreAliases = new Map([
  ["assert", require.resolve("assert/")],
  ["buffer", require.resolve("buffer/")],
  ["crypto", require.resolve("crypto-browserify")],
  ["path", require.resolve("path-browserify")],
  ["stream", require.resolve("stream-browserify")],
  ["url", require.resolve("url/")],
  ["util", require.resolve("util/")],
]);

const nodeCoreFallbackPlugin = {
  name: "node-core-fallback",
  setup(build) {
    build.onResolve({ filter: /^(assert|buffer|crypto|path|stream|url|util)$/ }, (args) => ({
      path: nodeCoreAliases.get(args.path),
    }));

    build.onResolve({ filter: /^node:(assert|buffer|crypto|path|stream|url|util)$/ }, (args) => ({
      path: nodeCoreAliases.get(args.path.slice("node:".length)),
    }));

    build.onResolve({ filter: /^(fs|http|https|os|vm)$/ }, (args) => ({
      path: args.path,
      namespace: "empty-module",
    }));

    build.onResolve({ filter: /^node:(fs|http|https|os|vm)$/ }, (args) => ({
      path: args.path.slice("node:".length),
      namespace: "empty-module",
    }));

    build.onLoad({ filter: /.*/, namespace: "empty-module" }, () => ({
      contents: "export default {};",
      loader: "js",
    }));
  },
};

// Replace the 'immediate' function inside localforage's bundled lie dependency
// to avoid dynamic <script> element creation which violates Obsidian's CSP.
// The immediate module has a chain: MutationObserver → setImmediate+MessageChannel
// → document.createElement("script") → setTimeout. We force the setTimeout path.
const immediateSafePlugin = {
  name: "immediate-safe",
  setup(build) {
    build.onLoad({ filter: /localforage[\/\\]dist[\/\\]localforage\.js$/ }, (args) => {
      const fs = require("fs");
      let contents = fs.readFileSync(args.path, "utf8");
      // Replace the entire module 1 (the immediate/asap implementation)
      // with a safe version that uses setTimeout.
      const safeModule1 =
        '1:[function(_dereq_,module,exports){(function(global){"use strict";' +
        'var draining;var queue=[];function nextTick(){draining=true;var i,oldQueue;' +
        'var len=queue.length;while(len){oldQueue=queue;queue=[];i=-1;' +
        'while(++i<len){oldQueue[i]()}len=queue.length}draining=false}' +
        'module.exports=function immediate(task){if(queue.push(task)===1&&!draining){setTimeout(nextTick,0)}}}' +
        ').call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})';
      contents = contents.replace(
        /1:\[function\(_dereq_,module,exports\)\{[\s\S]*?,\{\}\],2:/,
        safeModule1 + "\n},{}],2:"
      );
      return { contents, loader: "js" };
    });
  },
};

const copyDistFiles = () => {
  const distDir = path.join(process.cwd(), "dist");
  fs.mkdirSync(distDir, { recursive: true });

  for (const file of ["main.js", "manifest.json", "styles.css"]) {
    const src = path.join(process.cwd(), file);
    const dest = path.join(distDir, file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      console.log(`Copied ${file} to dist/`);
    }
  }
};

const buildOptions = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "main.js",
  format: "cjs",
  platform: "browser",
  target: "es2018",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  banner: {
    js: banner,
  },
  external,
  inject: ["./esbuild.buffer-shim.js"],
  define: {
    "process.env.DEFAULT_ONEDRIVE_CLIENT_ID": JSON.stringify(
      process.env.DEFAULT_ONEDRIVE_CLIENT_ID || ""
    ),
    "process.env.DEFAULT_ONEDRIVE_AUTHORITY": JSON.stringify(
      process.env.DEFAULT_ONEDRIVE_AUTHORITY || ""
    ),
    "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
    global: "globalThis",
  },
  plugins: [nodeCoreFallbackPlugin, immediateSafePlugin],
  logLevel: "info",
};

if (prod) {
  await esbuild.build(buildOptions);
  copyDistFiles();
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
  console.log("Watching for changes...");
}
